version: "3"
services:
  elixir_chat:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/elixir_chat
    ports:
      - 4000:4000
    environment:
      - MIX_ENV=dev
    depends_on:
      - postgres
    command: sleep infinity

  postgres:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres 

